.\" Manpage for marker.
.TH SIMUL 1 "7 JULY 2019" "1.0" "SIMUL man page"

.SH NAME
simul -  Dining philosopher problem solver

.SH SYNOPSIS
simul [OPTIONS]... [NUM]...
.SH DESCRIPTION
simul solves the dining philosopher problem and displays statics informations like average thinking time ,average eating time,average hungry time  

.SH OPTIONS
.BR \L --N
		N where N is the number of philosophers.	.BR
.BR \L --N
.BR \L --N
.BR \L --N

.SH SEE ALSO

.SH BUGS
No known bugs.
.SH COPYRIGHT 
UNLICENCED
.SH AUTHOR
Peiyi Guan (peiyiguan.yi@gmail.com)